---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/docker
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/scripts
  color: "0e8a16"
- name: area/jekyll
  color: "0e8a16"
- name: area/taskfile
  color: "0e8a16"


# =================================================================================================
# Renovate Types
# =================================================================================================
- name: renovate/ruby
  color: "027fa0"
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"


# =================================================================================================
# Semantic Types
# =================================================================================================
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
