
---
version: '3'

tasks:
  default:
    silent: true
    cmd: task -l

  jekyll:dev:
    desc: Start a development server that also builds future posts.
    dir: website
    cmd: bundle exec jekyll serve --incremental --future --drafts --livereload --force_polling

  jekyll:build:
    desc: Build the website.
    dir: website
    cmd: bundle exec jekyll build

  img:convert:
    desc: Convert all png images to webp and remove the originals.
    cmd: bash scripts/png_convert_to_webp.sh
