---
## ================================================================================================
## URL Settings
## ================================================================================================
# url: https://mirceanton.com
url: ""
baseurl: ""  # ??


## ================================================================================================
## Theme Settings
## ================================================================================================
theme: jekyll-theme-chirpy
theme_mode: dark


## ================================================================================================
## Locale Settings
## ================================================================================================
lang: en
timezone: Europe/Bucharest


## ================================================================================================
## Site Metadata
## ================================================================================================
title: Mircea Anton
tagline: DevOps by day, HomeOps by night!
description: In this blog I share my insights and experiences in the realm of devops and the tools and technologies I use in my home lab.
avatar: assets/img/icon.png
social_preview_image: assets/img/icon.png
social:
  name: Mircea-Pavel Anton
  email: hi@mirceanton.com
  links: [ https://www.mirceanton.com ]
github:
  username: mirceanton


## ================================================================================================
## Google Settings
## ================================================================================================
google_site_verification: ""  # TODO: fill in verification string
google_analytics:
  id: G-6C126MZNGT


## ================================================================================================
## Site Features Settings
## ================================================================================================
toc: true
paginate: 10

comments:
  active: giscus
  giscus:
    repo: mirceanton/mirceanton.com
    repo_id: R_kgDOLUY-RA
    category: Announcements
    category_id: DIC_kwDOLUY-RM4CdWUH
    mapping: title
    input_position: bottom
    lang: en
    reactions_enabled: 1
    theme: noborder_gray  # noborder_dark

pwa:
  enabled: false


# ------------ The following options are not recommended to be modified ------------------
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
